<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" 
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <title>XML Sitemap - Omni-Cast</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <style type="text/css">
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            color: #1e293b;
            background-color: #f8fafc;
            margin: 0;
            padding: 40px 20px;
          }
          .container {
            max-width: 1000px;
            margin: 0 auto;
            background: #fff;
            padding: 35px;
            border-radius: 16px;
            box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.05), 0 8px 10px -6px rgba(0, 0, 0, 0.05);
            border: 1px solid #e2e8f0;
          }
          .header-group {
            border-bottom: 2px solid #f1f5f9;
            padding-bottom: 24px;
            margin-bottom: 24px;
          }
          h1 {
            color: #0f172a;
            font-size: 28px;
            margin-top: 0;
            margin-bottom: 12px;
            font-weight: 800;
            display: flex;
            align-items: center;
            gap: 12px;
            letter-spacing: -0.025em;
          }
          h1 span {
            color: #3b82f6;
          }
          p.expl {
            color: #64748b;
            font-size: 14.5px;
            line-height: 1.6;
            margin: 0;
          }
          p.expl a {
            color: #2563eb;
            text-decoration: none;
            font-weight: 600;
          }
          p.expl a:hover {
            text-decoration: underline;
          }
          .stats {
            background-color: #f8fafc;
            border: 1px solid #e2e8f0;
            border-radius: 10px;
            padding: 12px 18px;
            font-size: 13.5px;
            color: #475569;
            display: inline-flex;
            align-items: center;
            gap: 8px;
            margin-bottom: 20px;
            font-weight: 500;
          }
          table {
            width: 100%;
            border-collapse: separate;
            border-spacing: 0;
            margin-top: 10px;
          }
          th {
            background-color: #f8fafc;
            color: #475569;
            font-weight: 700;
            text-align: left;
            padding: 14px 18px;
            font-size: 12.5px;
            border-bottom: 2px solid #e2e8f0;
            text-transform: uppercase;
            letter-spacing: 0.05em;
          }
          th:first-child {
            border-top-left-radius: 8px;
          }
          th:last-child {
            border-top-right-radius: 8px;
          }
          td {
            padding: 16px 18px;
            font-size: 14px;
            border-bottom: 1px solid #f1f5f9;
            color: #334155;
            vertical-align: middle;
          }
          tr:hover td {
            background-color: #f8fafc;
          }
          .loc-link {
            color: #2563eb;
            text-decoration: none;
            font-weight: 600;
            font-size: 14px;
          }
          .loc-link:hover {
            text-decoration: underline;
            color: #1d4ed8;
          }
          .badge {
            display: inline-flex;
            align-items: center;
            padding: 4px 10px;
            font-size: 11px;
            font-weight: 700;
            border-radius: 9999px;
            text-transform: uppercase;
            letter-spacing: 0.025em;
          }
          .badge-high {
            background-color: #dcfce7;
            color: #15803d;
          }
          .badge-med {
            background-color: #e0f2fe;
            color: #0369a1;
          }
          .badge-low {
            background-color: #f1f5f9;
            color: #475569;
          }
          .footer {
            margin-top: 35px;
            padding-top: 20px;
            border-top: 1px solid #e2e8f0;
            text-align: center;
            font-size: 12px;
            color: #94a3b8;
          }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header-group">
            <h1>Omni-Cast <span>XML Sitemap</span></h1>
            <p class="expl">
              Generated by Yoast-style sitemap engine, this XML Sitemap is optimized for search engine crawl consumption.
              You can find more information about XML sitemaps at <a href="https://sitemaps.org" target="_blank" rel="noopener noreferrer">sitemaps.org</a>.
            </p>
          </div>
          
          <div class="stats">
            <strong>Total Discovered Pages:</strong> <xsl:value-of select="count(sitemap:urlset/sitemap:url)"/>
          </div>
          
          <table>
            <thead>
              <tr>
                <th width="55%">URL Path</th>
                <th width="15%">Priority</th>
                <th width="15%">Change Frequency</th>
                <th width="15%">Last Modified</th>
              </tr>
            </thead>
            <tbody>
              <xsl:for-each select="sitemap:urlset/sitemap:url">
                <tr>
                  <td>
                    <a class="loc-link" href="{sitemap:loc}">
                      <xsl:value-of select="sitemap:loc"/>
                    </a>
                  </td>
                  <td>
                    <span>
                      <xsl:attribute name="class">
                        <xsl:choose>
                          <xsl:when test="sitemap:priority &gt;= 0.8">badge badge-high</xsl:when>
                          <xsl:when test="sitemap:priority &gt;= 0.5">badge badge-med</xsl:when>
                          <xsl:otherwise>badge badge-low</xsl:otherwise>
                        </xsl:choose>
                      </xsl:attribute>
                      <xsl:value-of select="sitemap:priority"/>
                    </span>
                  </td>
                  <td>
                    <span style="text-transform: capitalize;"><xsl:value-of select="sitemap:changefreq"/></span>
                  </td>
                  <td>
                    <xsl:value-of select="sitemap:lastmod"/>
                  </td>
                </tr>
              </xsl:for-each>
            </tbody>
          </table>
          
          <div class="footer">
            Omni-Cast © 2026. All rights reserved. Managed automatically via Omni-Cast distribution portal.
          </div>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
